### ISSUE TITLE
support themes 

### ISSUE THREAD

**Issue by behroozbc** [leNicDev/ng-hcaptcha#11]
hi please add support for themes 
[docs](https://docs.hcaptcha.com/configuration#themes)

**Comment by leNicDev** [comment]
Hi, there is an [undocumented [theme] property](https://github.com/leNicDev/ng-hcaptcha/blob/master/projects/ng-hcaptcha/src/lib/ng-hcaptcha.component.ts#L38) on the NgHcaptchaComponent. I will add it to the documentation.

**Comment by behroozbc** [comment]
thanks
