### ISSUE TITLE
Server-side rendering breaking

### ISSUE THREAD

**Issue by aeslinger0** [leNicDev/ng-hcaptcha#13]
There are a few issues when a component is included on a page that is server-side rendered. Please add null checks wherever `window` is being referenced. Also, since you do prevent the component from loading during SSR, the following line errors:

https://github.com/leNicDev/ng-hcaptcha/blob/7f855b32b72eb69b8349d32a4433ab2b9cd8dac3/projects/ng-hcaptcha/src/lib/ng-hcaptcha.component.ts#L102

with TypeError: Cannot read property 'unsubscribe' of undefined
    at NgHcaptchaComponent.ngOnDestroy

Could you add a null check here as well? Thank you

**Comment by leNicDev** [comment]
Hi @aeslinger0, thanks a lot for your feedback! I just added those null checks and released it with 1.0.0-beta.5.

**Comment by zawasp** [comment]
@leNicDev the `unsubscribe` null check is still missing, throwing exceptions on SSR. Using latest version, 1.2.0
`TypeError: Cannot read property 'unsubscribe' of undefined
    at NgHcaptchaComponent.ngOnDestroy (/app/dist/test/server/main.js:1:2364929)`
