### ISSUE TITLE
h captcha compatibility

### ISSUE THREAD

**Issue by lohnsonok** [leNicDev/ng-hcaptcha#15]
After installl and import in module .. Angular 11

`        NgHcaptchaModule.forRoot({
            siteKey: environment.hcaptcha_sitekey,
        }),
` 

Error: node_modules/ng-hcaptcha/lib/ng-hcaptcha.module.d.ts:3:22 - error NG6002: Appears in the NgModule.imports of LoginModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (ng-hcaptcha) which declares NgHcaptchaModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
    3 export declare class NgHcaptchaModule {
                           ~~~~~~~~~~~~~~~~
    src/app/main/login/login.module.ts:47:14 - error NG6002: Appears in the NgModule.imports of AppModule, but itself has errors
    
    47 export class LoginModule {

**Comment by Parziphal** [comment]
Since Angular 11 that error happens with _any_ new module you add to your app, until you launch `ng serve` again.

**Comment by lohnsonok** [comment]
> Since Angular 11 that error happens with _any_ new module you add to your app, until you launch `ng serve` again.

it worked thank you
