### ISSUE TITLE
Hey there!!  Fixed an issue with the language not getting set properly

### ISSUE THREAD

**Issue by jmauslein** [leNicDev/ng-hcaptcha#16]
I was trying to use your module to get hcaptcha working for our site, but ran into an issue where the language was not getting set properly on the captcha.   I added a setTimeout() to the load script to give another tick which allows it to get the updated config and apply it to the captcha prior to rendering.  

Hopefully you can use my patch to fix the issue.   

Thanks!
Justin Mauslein

[ng-hcaptcha+1.0.0-beta.3.patch.zip](https://github.com/leNicDev/ng-hcaptcha/files/6319106/ng-hcaptcha%2B1.0.0-beta.3.patch.zip)

**Comment by leNicDev** [comment]
Hi @jmauslein, thanks a lot for the patch! I actually had to increase the timeout to 50 ms for it to work reliably.
