### ISSUE TITLE
hCaptcha does not work with ionic android/ios

### ISSUE THREAD

**Issue by lebaphi** [leNicDev/ng-hcaptcha#20]
When I integrated the captcha into my angular hybrid application, it seems does not work on android or ios. I got this issue in the console:
```
File: https://newassets.hcaptcha.com/captcha/v1/eca8c00/static/hcaptcha-checkbox.html#id=00bumhqvnc4gr&host=localhost&sentry=true&reportapi=https%3A%2F%2Faccounts.hcaptcha.com&recaptchacompat=true&custom=false&tplinks=on&sitekey=xxxxxxxxxxx - Line 0 - Msg: Access to XMLHttpRequest at 'https://hcaptcha.com/checksiteconfig?host=localhost&sitekey=xxxxxxxxxx&sc=1&swa=1' from origin 'https://newassets.hcaptcha.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

I'm not sure how to resolve this?

Thanks,

**Comment by lebaphi** [comment]
![image](https://user-images.githubusercontent.com/26705621/126522715-884a6188-7dcd-42f3-92ca-7161d9a5ed58.png)
I find this one may resolve this issue above but can not add `localhost`?

**Comment by leNicDev** [comment]
Hi @lebaphi, hCaptcha is already aware of this problem and recommends this solution: https://docs.hcaptcha.com/#local-development

**Comment by lebaphi** [comment]
hi @leNicDev, thank you for your reply, this solution only works when we run this on the local browser. My issue is when I build my application to the ios/android application by ionic capacitor framework. Even though it's run on a mobile app, it's still a web app underneath, and it still uses the localhost domain. So how can I resolve this?

**Comment by lebaphi** [comment]
I can resolve this by this one https://capacitorjs.com/docs/config. Thanks
