### ISSUE TITLE
why use this ```"@angular/common": ">=6",```

### ISSUE THREAD

**Issue by behroozbc** [leNicDev/ng-hcaptcha#23]
hi 
why dont change this line below like this ```"@angular/common": ">=6",``` 
https://github.com/leNicDev/ng-hcaptcha/blob/e9aefb43b07a34c55324228734257d3940947e71/projects/ng-hcaptcha/package.json#L23

**Comment by lukasniestrat** [comment]
This is to make sure that the library only runs with the versions you have tested it with. If you write just >= 6 includes all versions greater than 6. If Angular v13 is released and the library is not compatible with it you will insert non-functioning code.

**Comment by behroozbc** [comment]
how often not compatible occur in new days angular ??

**Comment by lukasniestrat** [comment]
Nobody knows what the angular team will implement in the next versions.🔮
What is your problem with the notation? It should work with all current angular versions.

**Comment by leNicDev** [comment]
I agree with @lukasniestrat. I don't want to include versions that haven't been tested.

**Comment by behroozbc** [comment]
okay
