### ISSUE TITLE
IE 11 problem

### ISSUE THREAD

**Issue by tzortziskap** [leNicDev/ng-hcaptcha#24]
function loadHCaptcha(languageCode) syntax error in 
if (languageCode) {
            src += `&hl=${languageCode}`;
        }
browser gets confused with brackets please could you investigate it?

**Comment by leNicDev** [comment]
Hi @tzortziskap, which Angular version are you using? Angular recently dropped IE support.

**Comment by tzortziskap** [comment]
Hi Angular 8 and Angular js

**Comment by leNicDev** [comment]
Due to Angular dropping support for IE, I will close this issue.
