### ISSUE TITLE
Execute captcha programmatically

### ISSUE THREAD

**Issue by ronaldogiusti** [leNicDev/ng-hcaptcha#26]
Hi,
thank you for this component!
I wonder if it is or it will be possible to execute the captcha programmatically, as we can do with the **ng-recaptcha** component.
That would be really useful!

Best regards,
Ronaldo

**Comment by leNicDev** [comment]
Hi Ronaldo,

thank you very much for your request! With 1.2.0 you can execute the captcha programmatically by calling the `verify` function of the new `NgHcaptchaService`. You can find an example here:
https://github.com/leNicDev/ng-hcaptcha#execute-hcaptcha-programmatically

**Comment by ronaldogiusti** [comment]
Wow, that's awesome, and also pretty fast!
