### ISSUE TITLE
Refresh hCaptcha

### ISSUE THREAD

**Issue by xrickztahx** [leNicDev/ng-hcaptcha#27]
Stupid question, but how to refresh the hCaptcha programatically? like when hCaptcha gets expired

**Comment by Mickail** [comment]
Hi, i am not sure this is the best way to do it, but i managed to do something like this in my component typescript file:

eval("hcaptcha.reset()");

Hope this helps :)

**Comment by leNicDev** [comment]
Hi @xrickztahx the solution @Mickail mentioned works. The next update (1.3.0) will also contain a `reset` function. It will be included in the NgHcaptchaComponent and NgHcaptchaInvisibleButtonDirective.

**Comment by leNicDev** [comment]
see https://github.com/leNicDev/ng-hcaptcha/releases/tag/1.3.0
