### ISSUE TITLE
Enabling silent mode

### ISSUE THREAD

**Issue by wwoest** [leNicDev/ng-hcaptcha#36]
Would it perhaps be possible to expose a property to enable silent mode? Thanks!

**Comment by leNicDev** [comment]
Hi @wwoest do you mean the invisible mode? To do a silent verification in the background, you could use the `ngHcaptchaInvisibleButton` directive. You can find an example here: https://github.com/leNicDev/ng-hcaptcha#usage

**Comment by wwoest** [comment]
Much appreciated Nic! I will try out the directive, thanks.
