### ISSUE TITLE
Invisible Mode

### ISSUE THREAD

**Issue by wwoest** [leNicDev/ng-hcaptcha#38]
Good day. I'm trying to implement the invisible mode using ng-hcaptcha, however the only reference I could find is to use the ngHcaptchaInvisibleButton directive on a button. The requirement is to render the h-captcha checkbox and not a button, is this achievable using ng-hcaptcha Angular component? Something like the following (passing a size or data-size property): 

    <ng-hcaptcha
        size="invisible"
        [languageCode]="locale"
        (verify)="onVerify($event)"
        (expired)="onExpired()"
        (error)="onError($event)">
    </ng-hcaptcha>
    
Much appreciated in advance!

**Comment by leNicDev** [comment]
Hi @wwoest. This is not an official feature of hCaptcha. There's a possible workaround though:
1. Create a readonly checkbox
2. Add the ngHcaptchaInvisibleButton directive
3. Use the `(verify)` event to set the checkbox's checked state to `true`
