### ISSUE TITLE
invisible mode multiple calls to 'getcaptcha'

### ISSUE THREAD

**Issue by amitvocate** [leNicDev/ng-hcaptcha#41]
Hi,
While using invisible captcha with ngHcaptchaInvisibleButton, when clicking the button, it creates **3 calls** to `getcaptcha`, and it seems that it shows a challenge, then immediately changes it to something else.
besides that everything works, but it seems like something is wrong. maybe a bug.

Thanks!

**Comment by maidi29** [comment]
We observe the same problem in our application.
2 calls to getCaptcha happen on Button click and verify is called to times, too.
Would be great if this will be fixed! :) Thanks!

**Comment by amitvocate** [comment]
I've done a PR which have been tested in our app, and solves this issue.
please merge and issue a new version, so we can use it from npm.

**Comment by leNicDev** [comment]
@amitvocate Thanks a lot for fixing this? I will release a new version later today 👍🏼
