### ISSUE TITLE
Runtime Error with Webpack Build

### ISSUE THREAD

**Issue by colinbleach-inhealth** [leNicDev/ng-hcaptcha#43]
My angular 8 application has the package installed.
it is built using webpack and the project builds correctly however during runtime there is an undefined error.

The value target: i0.ɵɵFactoryTarget.Component  in the file ng-hcaptcha.mjs is undefined.
All of the samples use angular cli to build and run the projects, does this package support webpack built projects?

Here is the console error

![hcaptcha Error](https://user-images.githubusercontent.com/104559051/165713356-f8b9e4ba-f780-4a7d-87f7-ddd704c51451.PNG)

**Comment by leNicDev** [comment]
Hi @colinbleach-inhealth, thanks for reaching out! Please consider upgrading to the latest Angular version. Angular versions older than 11 are not supported anymore.

**Comment by colinbleach-inhealth** [comment]
Ok this is noted thanks for getting back to me.
