### ISSUE TITLE
hcaptcha not working with angular/core 7.1.0 

### ISSUE THREAD

**Issue by felipeheld** [leNicDev/ng-hcaptcha#48]
So, pretty straightforward, I guess. The module isn't working as expected with angular/core version 7.1.0.

package.json dependencies:

`"dependencies": {
    "@angular/animations": "~7.1.0",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/http": "~7.1.0",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "~7.1.0",
    "@fortawesome/fontawesome-free": "^5.4.0",
    "@ng-bootstrap/ng-bootstrap": "^3.3.1",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "bootstrap": "^4.3.1",
    "core-js": "^2.5.4",
    "file-saver": "^2.0.2",
    "ng-bootstrap-form-validation": "^3.0.3",
    "ngx-translate-multi-http-loader": "^2.1.2",
    "node-sass": "^4.12.0",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.11.4",
    "@angular-devkit/build-ng-packagr": "~0.11.0",
    "@angular/cli": "~7.3.8",
    "@angular/compiler-cli": "~7.1.0",
    "@angular/language-service": "~7.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "https-proxy-agent": "^2.2.4",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^4.2.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tsickle": ">=0.29.0",
    "tslib": "^1.9.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }`

html:

`<ng-hcaptcha
              formControlName="captcha"
              siteKey="<MY_SITE_KEY>"
              (verify)="onCaptchaVerify($event)">
 </ng-hcaptcha>`

Module import (omitted other modules for brevity and what not):
`@NgModule({
  imports: [
     NgHcaptchaModule.forRoot()
  ]
`

The errors:
`ERROR in node_modules/ng-hcaptcha/lib/ng-hcaptcha-invisible-button.directive.d.ts(38,21): error TS2694: Namespace '"C:/Users/felipe.izquierdo/Desktop/PITA/cloud-ui/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
node_modules/ng-hcaptcha/lib/ng-hcaptcha-invisible-button.directive.d.ts(39,21): error TS2694: Namespace '"C:/Users/felipe.izquierdo/Desktop/PITA/cloud-ui/node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration'.
node_modules/ng-hcaptcha/lib/ng-hcaptcha.component.d.ts(30,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/ng-hcaptcha/lib/ng-hcaptcha.component.d.ts(31,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/ng-hcaptcha/lib/ng-hcaptcha.component.d.ts(47,21): error TS2694: Namespace '"C:/Users/felipe.izquierdo/Desktop/PITA/cloud-ui/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
node_modules/ng-hcaptcha/lib/ng-hcaptcha.component.d.ts(48,21): error TS2694: Namespace '"C:/Users/felipe.izquierdo/Desktop/PITA/cloud-ui/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.
node_modules/ng-hcaptcha/lib/ng-hcaptcha.module.d.ts(8,21): error TS2694: Namespace '"C:/Users/felipe.izquierdo/Desktop/PITA/cloud-ui/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
node_modules/ng-hcaptcha/lib/ng-hcaptcha.module.d.ts(9,21): error TS2694: Namespace '"C:/Users/felipe.izquierdo/Desktop/PITA/cloud-ui/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.
node_modules/ng-hcaptcha/lib/ng-hcaptcha.module.d.ts(10,21): error TS2694: Namespace '"C:/Users/felipe.izquierdo/Desktop/PITA/cloud-ui/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.
node_modules/ng-hcaptcha/lib/ng-hcaptcha.service.d.ts(11,21): error TS2694: Namespace '"C:/Users/felipe.izquierdo/Desktop/PITA/cloud-ui/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
node_modules/ng-hcaptcha/lib/ng-hcaptcha.service.d.ts(12,22): error TS2694: Namespace '"C:/Users/felipe.izquierdo/Desktop/PITA/cloud-ui/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.`

No sensitive information, and I believe I got everything properly. Obviously, I might be missing something, and if the issue is lacking any relevant information, please let me know.

**Comment by leNicDev** [comment]
Hi @felipeheld, the current version only supports Angular 9-15. Version 1.3.1 should still support Angular 7.
