### ISSUE TITLE
Idea / Request: Invisible Captcha

### ISSUE THREAD

**Issue by palmersu** [leNicDev/ng-hcaptcha#5]
First, thank you!  This is awesome and very helpful.
I've tried for a while to get the invisible captcha to work with this but I can't seem to make it work.  I was wondering if you have given any thought to including invisible captcha? 

https://docs.hcaptcha.com/invisible

**Comment by leNicDev** [comment]
Hi @palmersu , thanks for your feature request! It has been added with the latest beta release:
https://github.com/leNicDev/ng-hcaptcha/releases/tag/1.0.0-beta.0

I will close this issue new. Feel free to re-open it if you have additional ideas 😄

**Comment by palmersu** [comment]
Awesome, thank you so much!
