### ISSUE TITLE
[SSR] When calling ngOnDestroy in ng-hcaptcha.component.ts

### ISSUE THREAD

**Issue by detmot5** [leNicDev/ng-hcaptcha#54]
I found following issue when using SSR :

``` ts
  ngOnDestroy() {
    this.captcha$.unsubscribe();
  }
```
While using SSR, this.captcha$ is undefined because it's not set in ngOnInit()
The solution would be:

```
ngOnDestroy() {
  if(isPlatformServer(this.platformId) {
     retrun
  }
  // the rest of code 
}
```

**Comment by leNicDev** [comment]
Hi @detmot5, thank you very much for reporting this issue! It will be fixed in the next release (2.1.0).
