### ISSUE TITLE
Language Codes

### ISSUE THREAD

**Issue by behroozbc** [leNicDev/ng-hcaptcha#6]
hi 
can you add language codes in config module

**Comment by leNicDev** [comment]
Hi @behroozbc, I'm working on it. Currently the hCaptcha API seems to return the same script regardless of the language code passed.
`api.js?hl=de` and `api.js?hl=en` both seem to redirect to the same script.

**Comment by behroozbc** [comment]
hi @leNicDev 
i test in fa for Persian 
https://typescript-hxy852.stackblitz.io
translate to Persian language worked

**Comment by behroozbc** [comment]
Hi @leNicDev 
can you test in server not in localhost ?

**Comment by leNicDev** [comment]
I managed to get it working. It has just been released:
https://github.com/leNicDev/ng-hcaptcha/releases/tag/1.0.0-beta.1

**Comment by behroozbc** [comment]
hi 
thanks

**Comment by behroozbc** [comment]
hi @leNicDev  
I use ng-hcaptcha in [this](https://app.radaqco.com/Authentication) website and set language code to fa for Persian but show me English

**Comment by leNicDev** [comment]
hi @behroozbc 
Thanks for reporting the issue. I will look into it.

**Comment by behroozbc** [comment]
hi 
@leNicDev 
I find couple time register script tag 
you can see in [this](https://app.radaqco.com)
![image](https://user-images.githubusercontent.com/20381616/99180519-104dfe80-273c-11eb-97d1-b66b52761dfc.png)

**Comment by NickTheGre13** [comment]
Any updates on this issue?

**Comment by leNicDev** [comment]
Hi @behroozbc @NickTheGre13 I will look into this issue tomorrow. Sorry for the delay.

**Comment by leNicDev** [comment]
@NickTheGre13 @behroozbc It seems to be an issue with hCaptcha. When loading the hCaptcha script with `render=explicit`, the `hl` parameter seems to be ignored. When removing `render=explicit`, it works. I already contacted hCaptcha and will keep you updated.

**Comment by behroozbc** [comment]
@leNicDev hi 
any update on this issue ??

**Comment by jmauslein** [comment]
I added a patch that fixes the language issue:
https://github.com/leNicDev/ng-hcaptcha/issues/16

**Comment by leNicDev** [comment]
This has been fixed by @jmauslein's patch. Please upgrade to 1.0.0-beta.5
