### ISSUE TITLE
ng-hcaptcha is not working with angular version 8.2.14

### ISSUE THREAD

**Issue by rashidhamid21** [leNicDev/ng-hcaptcha#64]
Hi Team,

ng-hcaptcha is not working in my angular application(version-8.2.14). I am using the ng-hcaptcha version "1.3.1". It is showing below errors at the time of ng serve.

**ng-hcaptcha errors**

ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 148:18-27
Can't import the named export 'Component' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 278:18-27
Can't import the named export 'Directive' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 275:179-192
Can't import the named export 'ElementRef' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 283:24-37
Can't import the named export 'ElementRef' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 49:26-38
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 50:27-39
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 51:25-37
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 196:26-38
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 197:27-39
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 198:25-37
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 199:25-37
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 303:22-34
Can't import the named export 'HostListener' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 163:30-36
Can't import the named export 'Inject' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 166:30-36
Can't import the named export 'Inject' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 284:30-36
Can't import the named export 'Inject' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 287:30-36
Can't import the named export 'Inject' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 360:30-36
Can't import the named export 'Inject' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 357:18-28
Can't import the named export 'Injectable' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 7:27-41
Can't import the named export 'InjectionToken' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 170:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 172:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 174:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 176:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 178:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 291:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 293:22-27
Can't import the named export 'Input' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 142:21-38
Can't import the named export 'NG_VALUE_ACCESSOR' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 155:37-54
Can't import the named export 'NG_VALUE_ACCESSOR' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 383:18-26
Can't import the named export 'NgModule' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 139:176-185
Can't import the named export 'NgZone' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 165:34-43
Can't import the named export 'NgZone' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 275:232-241
Can't import the named export 'NgZone' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 286:34-43
Can't import the named export 'NgZone' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 15:15-25
Can't import the named export 'Observable' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 312:19-29
Can't import the named export 'Observable' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 183:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 185:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 187:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 295:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 297:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 299:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 301:22-28
Can't import the named export 'Output' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 139:198-209
Can't import the named export 'PLATFORM_ID' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 167:31-42
Can't import the named export 'PLATFORM_ID' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 275:254-265
Can't import the named export 'PLATFORM_ID' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 288:31-42
Can't import the named export 'PLATFORM_ID' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 180:22-31
Can't import the named export 'ViewChild' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 143:25-35
Can't import the named export 'forwardRef' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 156:41-51
Can't import the named export 'forwardRef' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 94:12-29
Can't import the named export 'isPlatformBrowser' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 242:12-29
Can't import the named export 'isPlatformBrowser' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 62:12-28
Can't import the named export 'isPlatformServer' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 207:12-28
Can't import the named export 'isPlatformServer' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 227:12-28
Can't import the named export 'isPlatformServer' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 139:222-240
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 275:278-296
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 354:172-190
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 379:145-163
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 147:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 277:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 356:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 382:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 140:27-50
Can't import the named export 'ɵɵngDeclareComponent' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 276:42-65
Can't import the named export 'ɵɵngDeclareDirective' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 139:27-48
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 275:42-63
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 354:25-46
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 379:24-45
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 355:26-50
Can't import the named export 'ɵɵngDeclareInjectable' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 381:24-46
Can't import the named export 'ɵɵngDeclareInjector' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs 380:24-46
Can't import the named export 'ɵɵngDeclareNgModule' from non EcmaScript module (only default export is available)

**package.json dependencies**

"dependencies": {
    "-": "0.0.1",
    "@angular/animations": "8.2.14",
    "@angular/cdk": "8.1.1",
    "@angular/common": "8.2.14",
    "@angular/compiler": "8.2.14",
    "@angular/core": "8.2.14",
    "@angular/forms": "8.2.14",
    "@angular/platform-browser": "8.2.14",
    "@angular/platform-browser-dynamic": "8.2.14",
    "@angular/router": "8.2.14",
    "@azure/msal-angular": "2.4.1",
    "@ng-bootstrap/ng-bootstrap": "5.0.0",
    "@ng-select/ng-select": "^3.0.0",
    "@types/jquery": "3.3.1",
    "bootstrap": "4.4.1",
    "core-js": "3.1.4",
    "crypto-js": "4.1.1",
    "font-awesome": "4.7.0",
    "g": "2.0.1",
    "jquery": "3.5.1",
    "msal": "0.2.3",
    "ng-hcaptcha": "1.3.1",
    "popper.js": "1.16.1",
    "rxjs": "6.5.4",
    "tree-kill": "1.2.2",
    "tslib": "1.10.0",
    "yargs-parser": "15.0.1",
    "zone.js": "0.9.1"
  },

**Component html**
 <ng-hcaptcha
                                iteKey="<MY_SITE_KEY>"
                                (verify)="onVerify($event)"
                            </ng-hcaptcha>

**Component typescript**

 constructor(private hcaptchaService: NgHcaptchaService,
    ) {
        this.nghcaptchaService = new NgHcaptchaService({
            siteKey : '<myhcaptchakey>'
        })
}

onVerify() {
        console.log("this.hcaptchaService>>>", this.hcaptchaService);
        this.hcaptchaService.verify().subscribe(
          (result) => {
            console.log('SUCCESS', result);
          },
          (err) => {
            console.log('FAILED', err);
          },
          () => {
            console.log('COMPLETE');
          }
        );
    }

**app.module.ts** 

@NgModule({ imports: [....,
 NgHcaptchaModule.forRoot() ] 

**One more point.** 
ng-hcaptcha 2.0.0 or later version i have tried but it is also not installing in my angular application. It is showing below error.
so i installed the 1.3.1 and 1.3.1 version is installed successfully.  

npm install ng-hcaptcha@^2.0.0
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: client-app@1.34.0
npm ERR! Found: @angular/common@8.2.14
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"8.2.14" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0" from ng-hcaptcha@2.0.0
npm ERR! node_modules/ng-hcaptcha
npm ERR!   ng-hcaptcha@"2.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\s1pwch\AppData\Local\npm-cache\eresolve-report.txt for a full report.

I believe that I have provided the enough information related to this issue if anything further is required, please let me know.

Kindly provide the solution for this issue as soon as possible. **Thanks in advance. **

**Comment by leNicDev** [comment]
Please consider upgrading to a newer version of Angular. ng-hcaptcha only supports LTS versions (v14) or later. The other solution in your case would be using an older version of ng-hcaptcha.

**Comment by rashidhamid21** [comment]
After the Angular version upgrade now ng-hcaptcha is working
