### ISSUE TITLE
ERROR in ./node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs Module build failed: Error: ENOENT: no such file or directory, open '/Users/penalozajohn25/proyectos/AISA/jakue_panel/node_modules/ng-hcaptcha/fesm2015/ng-hcaptcha.mjs'

### ISSUE THREAD

**Issue by penalozajohn25** [leNicDev/ng-hcaptcha#69]
How to solve this detail ?  please I'm with Angular 6

**Comment by leNicDev** [comment]
Hi @penalozajohn25, the latest version of ng-hcaptcha only support Angular 9+. If you can't upgrade your app, try using an earlier version of ng-hcaptcha (1.0.0-beta versions should be working).
