### ISSUE TITLE
CORS blocked

### ISSUE THREAD

**Issue by behroozbc** [leNicDev/ng-hcaptcha#7]
hi 
I want use hcaptcha i get cors error 
![image](https://user-images.githubusercontent.com/20381616/87224635-2f0e4400-c39c-11ea-8abb-94798df50095.png)

**Comment by leNicDev** [comment]
Hi @behroozbc you can't use hCaptcha on localhost. Please see the hCaptcha documentation:
https://docs.hcaptcha.com/#localdev

**Comment by leNicDev** [comment]
Closed due to inactivity. Feel free to reopen the issue if needed.
