### ISSUE TITLE
TS1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by levz0r** [leNicDev/ng-hcaptcha#8]
Hello,

We are using Angular 8.2.14. After adding `NgHcaptchaModule` to our project, the project is not compiling anymore.
There reason is as following:
![image](https://user-images.githubusercontent.com/4564386/89773904-7ad41a80-db0d-11ea-8fdd-36afb59065a5.png)
Angular 8 is requiring to have Typescript version below 3.6.0, so upgrading is not an option.
Any suggestions please?

**Comment by leNicDev** [comment]
Thanks for reporting the issue. Could you try using ng-hcaptcha@1.0.0-beta.1?

**Comment by levz0r** [comment]
@leNicDev thank you for the prompt reply. It still doesn't work with beta.1...

**Comment by leNicDev** [comment]
@levz0r I will release a hotfix as soon as I can. Setting `"skipLibCheck": true` in your tsconfig.json should temporarily fix the issue for now.

**Comment by leNicDev** [comment]
Closing this as Angular 8 is no longer supported.
See https://angular.io/guide/releases#support-policy-and-schedule
