### ISSUE TITLE
Changing styles on puzzle pop-up

### ISSUE THREAD

**Issue by gabbriela** [leNicDev/ng-hcaptcha#81]
Hello, 

I am trying to change the styles on the pop-up that comes out for solving a puzzle. I need it to align with my other styles. 

I see there is **`theme`** property, same as the **`sitekey`**, but when I add it, it is not a valid property.

Do I need an additional step or am I missing something? 

Thank you!

**Comment by leNicDev** [comment]
Theming is implemented inside the hCaptcha library. It currently supports the following themes: https://docs.hcaptcha.com/configuration/#themes
