### ISSUE TITLE
How to make it this work in Localhost 

### ISSUE THREAD

**Issue by azharmn123** [leNicDev/ng-hcaptcha#88]
I am trying in my local and it giving me error The sitekey for this hCaptcha is incorrect. Please contact the site admin if you see this.

**Comment by JohanHeyvaert** [comment]
This question is not specific for this library. Cf. the documentation of hCaptcha.
For local development you can use a test key, which is mentioned here: https://docs.hcaptcha.com/#integration-testing-test-keys

Best regards,
Johan

**Comment by azharmn123** [comment]
Thanks for your reply. I have implemented hcaptcha. For localhost i am just geting warning. I am good now.
